/**
 * language:gen — Merge raw i18n JSON files & generate TypeScript interface
 *
 *   assets/language/raw/en/*.json  ───────────────────┐
 *   assets/language/raw/vi/*.json  ──► merge ──► en.json / vi.json
 *                                                        │
 *   Recursively walk merged tree ────────────────────────┘
 *              │
 *              ▼
 *   src/types/languageText.ts   (auto‑generated)
 *
 * Usage:  node __script_/languageGen.js
 *         npm run language:gen
 */
/* eslint-env node */
const fs = require('fs');
const path = require('path');

const RAW_BASE = path.resolve(__dirname, '..', 'assets', 'language', 'raw');
const OUT      = path.resolve(__dirname, '..', 'assets', 'language');
const TYPES    = path.resolve(__dirname, '..', 'src', 'types', 'languageText.ts');

const LOCALES    = ['en', 'vi'];

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Deep‑merge `src` into `target` (mutates target). */
function deepMerge(target, src) {
  for (const key of Object.keys(src)) {
    if (src[key] !== null && typeof src[key] === 'object' && !Array.isArray(src[key])) {
      if (!target[key] || typeof target[key] !== 'object') target[key] = {};
      deepMerge(target[key], src[key]);
    } else {
      target[key] = src[key];
    }
  }
  return target;
}

/** Read, parse & merge all *.json files inside a locale directory. */
function loadLocale(locale) {
  const dir = path.join(RAW_BASE, locale);
  if (!fs.existsSync(dir)) {
    console.warn(`  ⚠  locale directory not found: ${dir}`);
    return {};
  }
  const files = fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort();
  const merged = {};
  for (const file of files) {
    const raw = fs.readFileSync(path.join(dir, file), 'utf-8');
    try {
      const parsed = JSON.parse(raw);
      deepMerge(merged, parsed);
    } catch (e) {
      console.error(`  ✖  Parse error in ${locale}/${file}: ${e.message}`);
    }
  }
  return merged;
}

// ── Type‑interface generation ────────────────────────────────────────────────

/** PascalCase + sanitise a dotted‑path segment for use as an interface name. */
function toPascalCase(str) {
  return str
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .replace(/(?:^|_)([a-zA-Z])/g, (_, c) => c.toUpperCase());
}

/** Generate the full `LanguageText` interfaces from a merged object. */
function generateInterfaces(localeData) {
  // We generate from the *first* locale (assumed to be the canonical one,
  // typically `en`). The interface must cover every key across all locales,
  // so we union all keys first.
  const lines = [];
  lines.push('// ⚠️  Auto‑generated by `language:gen`. Do not edit manually.');
  lines.push('');
  lines.push('export interface LanguageText {');

  for (const [key, value] of Object.entries(localeData)) {
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      const subName = `LanguageText${toPascalCase(key)}`;
      lines.push(`  ${key}: ${subName};`);
    } else {
      lines.push(`  ${key}: string;`);
    }
  }

  lines.push('}');

  // Recursively emit child interfaces
  for (const [key, value] of Object.entries(localeData)) {
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      const subName = `LanguageText${toPascalCase(key)}`;
      lines.push('');
      lines.push(`export interface ${subName} {`);
      emitChildInterfaces(lines, value, 1, `LanguageText${toPascalCase(key)}`);
      lines.push('}');
    }
  }

  return lines.join('\n');
}

function emitChildInterfaces(lines, obj, depth, parentName) {
  const indent = '  '.repeat(depth);
  for (const [key, value] of Object.entries(obj)) {
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      const subName = `${parentName}${toPascalCase(key)}`;
      lines.push(`${indent}${key}: ${subName};`);
      lines.push(`${indent}}`);
      lines.push(`\n${indent}export interface ${subName} {`);
      emitChildInterfaces(lines, value, depth + 1, subName);
      lines.push(`${indent}}`);
    } else {
      lines.push(`${indent}${key}: string;`);
    }
  }
}

// ── Coverage validation ──────────────────────────────────────────────────────

/** Walk all leaf‑paths of a nested object. */
function leafPaths(obj, prefix = '') {
  const paths = [];
  for (const [key, value] of Object.entries(obj)) {
    const p = prefix ? `${prefix}.${key}` : key;
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      paths.push(...leafPaths(value, p));
    } else {
      paths.push(p);
    }
  }
  return paths;
}

// ── Main ─────────────────────────────────────────────────────────────────────

function main() {
  console.log('\n  🔤  language:gen  🔤\n');

  // 1. Load & merge per locale
  const merged = {};
  for (const locale of LOCALES) {
    merged[locale] = loadLocale(locale);
  }

  // 2. Validate coverage (all locales must have the same leaf keys)
  const keySets = {};
  for (const locale of LOCALES) {
    keySets[locale] = new Set(leafPaths(merged[locale]));
  }

  const allKeys = new Set();
  for (const locale of LOCALES) {
    for (const k of keySets[locale]) allKeys.add(k);
  }

  let hasMissing = false;
  for (const locale of LOCALES) {
    const missing = [...allKeys].filter(k => !keySets[locale].has(k));
    if (missing.length > 0) {
      console.warn(`  ⚠  ${locale} is missing keys:`);
      missing.forEach(k => console.warn(`        ${k}`));
      hasMissing = true;
    }
  }
  if (!hasMissing) {
    console.log(`  ✓  i18n coverage: all ${LOCALES.length} locales have the same set of keys.`);
  } else {
    console.warn('\n  ⚠  Some locales are missing keys. The generated interface will');
    console.warn('      include all keys, but missing ones will be undefined at runtime.');
    console.warn('      Make sure to add them before shipping.\n');
  }
  console.log();

  // 3. Write merged JSON files (pretty‑printed)
  for (const locale of LOCALES) {
    const outPath = path.join(OUT, `${locale}.json`);
    fs.writeFileSync(outPath, JSON.stringify(merged[locale], null, 2) + '\n');
    console.log(`  ✓  Wrote  ${locale}.json`);
  }

  // 4. Generate & write TypeScript interface using the *union* of all keys
  //    Build the union object manually so union keys appear in the interface.
  const union = {};
  for (const locale of LOCALES) {
    deepMerge(union, merged[locale]);
  }

  const interfaceCode = generateInterfaces(union);
  fs.writeFileSync(TYPES, interfaceCode + '\n');
  console.log(`  ✓  Wrote  src/types/languageText.ts\n`);

  // 5. Summary
  const totalFiles = LOCALES.reduce((sum, l) => {
    const dir = path.join(RAW_BASE, l);
    return sum + (fs.existsSync(dir) ? fs.readdirSync(dir).filter(f => f.endsWith('.json')).length : 0);
  }, 0);
  const totalKeys = allKeys.size;
  console.log(`  📊  Summary`);
  console.log(`       locales   : ${LOCALES.length} (${LOCALES.join(', ')})`);
  console.log(`       modules   : ${totalFiles} JSON files total`);
  console.log(`       leaf keys : ${totalKeys}`);
  console.log('');
}

main();